[package]
name        = "const_type"
version     = "0.1.0"
authors     = ["sivizius <sivizius@ohai.su>"]
edition     = "2018"
license     = "MIT"
repository  = "https://github.com/sivizius/const_type"

[dependencies]
